# List of users with access to the bot's code
# Updates to this list require a full restart
owners = [
    "legoktm",
    "majavah",
]
# List of users who can merge changes to config
# Updates to this list require a full restart
trusted = [
    "Legoktm",
    "majavah",
]

password_file = "/data/project/ircservserv/password"
channel_config = "/data/project/ircservserv/ircservserv-config"

[irc]
# Channels that this bot manages
channels = [
    "#wikimedia-ops",
    "#mediawiki",
    "#pywikibot",
    "#wikimedia-dev",
    "#wikimedia-editing",
    "#wikimedia-hackathon",
    "#wikimedia-kawaii",
    "#wikimedia-operations",
    "#wikimedia-serviceops",
    "#wikimedia-sre",
]
# IRC bot settings
owners = []
nickname = "ircservserv-wm"
alt_nicks = ["ircservserv-wm_", "ircservserv-wm__"]
username = "wm-ircservserv"
realname = "Hmmmmm"
server = "irc.libera.chat"
port = 6697
use_tls = true
encoding = "UTF-8"
user_info = "Bots go beep beep."
version = "0.0.0"
