owners = []
nickname = "wm-ircservserv"
alt_nicks = ["wm-ircservserv_", "wm-ircservserv__"]
username = "wm-ircservserv"
realname = "Hmmmmm"
server = "irc.libera.chat"
port = 6697
use_tls = true
encoding = "UTF-8"
channels = ["#wikimedia-ops", "#mediawiki", "#wikimedia-kawaii"]
user_info = "Bots go beep beep."
version = "0.0.0"

[options]
password_file = "/data/project/ircservserv/password"
channel_config = "/data/project/ircservserv/ircservserv-config"
