password_file = "/data/project/ircservserv/password"
channel_config = "/data/project/ircservserv/ircservserv-config"
trusted = [
    "user/legoktm",
]

[irc]
owners = []
nickname = "wm-ircservserv_"
alt_nicks = ["ircservserv-wm", "wm-ircservserv__"]
username = "wm-ircservserv"
realname = "Hmmmmm"
server = "irc.libera.chat"
port = 6697
use_tls = true
encoding = "UTF-8"
channels = [
    "#wikimedia-ops",
    "#mediawiki",
    "#pywikibot",
    "#wikimedia-dev",
    "#wikimedia-hackathon",
    "#wikimedia-kawaii",
    "#wikimedia-operations",
    "#wikimedia-serviceops",
    "#wikimedia-sre",
]
user_info = "Bots go beep beep."
version = "0.0.0"
