founders = [
    "arlolra",
    "cscott",
    "subbu",
    "ircservserv-wm",
]
crats = [
    "TimStarling",
    "ihurbain",
    "legoktm",
    "sbailey",
]
ops = [
    "James_F",
    "Kemayo",
    "Majavah",
    "Reedy",
]
plus_o = [
]
autovoice = [
    # Team members
    "arlolra",
    "cscott",
    "subbu",
    "ihurbain",
    "sbailey",
    # Bots
    "wikibugs",
    "wmopbot",
]
global_bans = true
libera_staff = true
wmopbot = true
