founders = [
    "TimStarling",
    "legoktm",
    "ircservserv-wm",
]
crats = [
]
ops = [
    "AntiComposite",
    "Ciencia-Al-Poder",
    "Isarra",
    "Nikerabbit",
    "Platonides",
    "Reedy",
    "hashar",
    "moonmoon",
    "p858snake",
    "snowolf",
    "stwalkerster",
    "Urbanecm",
    "ashley",
    "c",
    "[1997kB]",
]
plus_o = [
    "wmopbot",
]
global_bans = true
libera_staff = true
