founders = [
    "Az1568",
    "legoktm",
    "ircservserv-wm",
]
crats = [
    "JJMC89",
    "valhallasw",
    "andre",
    "Amir1",
]
ops = [
    "c",
]
plus_o = [
    "*!*@libera/staff/*",
    "litharge",
    "wmopbot",
]
autovoice = [
    "ircservserv-wm",
    "litharge",
    "wikibugs",
    "wmopbot",
]
global_bans = true
