founders = [
    "Az1568",
    "legoktm",
]
crats = [
    "JJMC89",
    "valhallasw",
    "andre",
    "Amir1"
]
ops = [
    "c",
]
plus_o = [
    "*!*@libera/staff/*",
    "wmopbot",
]
global_bans = true
