founders = [
    "joe_oblivian",
    "paravoid",
    "ircservserv-wm",
]
crats = [
    "legoktm",
    "akosiaris",
]
ops = [
    "manuel",
    "sirenbot",
]
plus_o = [
]
global_bans = true
libera_staff = true
wmopbot = true
