founders = [
    "Az1568",
    "legoktm",
    "joe_oblivian",
    "ircservserv-wm",
]
crats = [
]
ops = [
    "manuel",
]
plus_o = [
    "*!*@libera/staff/*",
    "wmopbot",
]
autovoice = [
    "icinga-wm",
    "ircservserv-wm",
    "jinxer-wm",
    "jouncebot",
    "logmsgbot",
    "stashbot",
    "wikibugs",
    "wmopbot",
    "wm-bot",
]
global_bans = true
