founders = [
    "Az1568",
    "ircservserv-wm",
    "ebernhardson",
    "gehel",
]
crats = [
    "dcausse",
    "inflatador",
    "mpham",
    "pfischer",
    "ryankemper",
    "Trey314159",
    "zpapierski",
]
ops = [
]
plus_o = [
    "wmopbot",
]
autovoice = [
    "dcausse",
    "ebernhardson",
    "gehel",
    "inflatador",
    "mpham",
    "pfischer",
    "ryankemper",
    "Trey314159",
    "zpapierski",
]
global_bans = true
libera_staff = true
