founders = [
    "ircservserv-wm",
    "ebernhardson",
    "gehel",
]
crats = [
    "dcausse",
    "dr0ptp4kt",
    "inflatador",
    "mpham",
    "pfischer",
    "ryankemper",
    "Trey314159",
]
ops = [
]
plus_o = [
]
autovoice = [
    "dcausse",
    "dr0ptp4kt",
    "ebernhardson",
    "gehel",
    "inflatador",
    "mpham",
    "pfischer",
    "ryankemper",
    "Trey314159",
]
global_bans = true
libera_staff = true
wmopbot = true
