founders = [
    "joe_oblivian",
    "legoktm",
    "ircservserv-wm",
]
crats = [
    "akosiaris",
    "claime",
    "effie",
    "jayme",
    "kavitha",
    "mutante",
    "rzl",
]
ops = [
]
plus_o = [
]
autovoice = [
    "wikibugs",
]
global_bans = true
libera_staff = true
wmopbot = true
