founders = [
    "Az1568",
    "legoktm",
    "ircservserv-wm",
]
crats = [
]
ops = [
    "Amir1",
    "Isarra",
    "Lucas_WMDE",
    "quiddity",
    "Reedy",
]
plus_o = [
    "wmopbot",
]
global_bans = true
libera_staff = true
