founders = [
    "ircservserv-wm",
    "Krinkle",
]
crats = [
    "AaronSchulz",
    "dpifke",
    "Krinkle",
    "lgaulia",
    "phedenskog",
    "TimStarling",
]
ops = []
plus_o = [
    "wmopbot",
]
autovoice = [
    "AaronSchulz",
    "dpifke",
    "Krinkle",
    "lgaulia",
    "phedenskog",
    "TimStarling",
]
global_bans = true
libera_staff = true
