founders = [
    "Az1568",
    "Kemayo",
    "James_F",
    "ircservserv-wm",
]
crats = [
    "MatmaRex",
    "ryasmeen",
]
ops = [
    "legoktm",
]
plus_o = [
    "*!*@libera/staff/*",
    "wmopbot",
]
global_bans = true
