founders = [
    "ircservserv-wm",
    "akosiaris",
    "joe_oblivian",
]
crats = [
    "jayme",
    "elukey",
    "btullis",
]
ops = [
]
plus_o = [
    "wmopbot",
]
autovoice = [
]
global_bans = true
libera_staff = true
