founders = [
    "Az1568",
    "legoktm",
    "joe_oblivian",
    "ircservserv-wm",
]
crats = [
]
ops = [
    "akosiaris",
    "apergos",
    "bd808",
    "dancy",
    "effie",
    "Emperor",
    "greg-g",
    "hashar",
    "Isarra",
    "James_F",
    "jbond",
    "jynus",
    "klausman",
    "Lucas_WMDE",
    "manuel",
    "Nikerabbit",
    "ottomata",
    "paravoid",
    "question_mark",
    "Reedy",
    "sbassett",
    "shdubsh",
    "thcipriani",
    "Urbanecm",
    "vgutierrez",
    "volans",
    "wiki_willy",
    "XioNoX",
]
plus_o = [
    "wmopbot",
]
autovoice = [
    "icinga-wm",
    "ircservserv-wm",
    "jinxer-wm",
    "jouncebot",
    "logmsgbot",
    "stashbot",
    "wikibugs",
    "wmopbot",
    "wm-bot",
]
global_bans = true
libera_staff = true
