founders = [
    "Az1568",
    "joe_oblivian",
    "paravoid",
    "ircservserv-wm",
]
crats = [
    "legoktm",
    "akosiaris",
]
ops = [
    "manuel",
    "sirenbot",
]
plus_o = [
    "wmopbot",
]
global_bans = true
libera_staff = true
