founders = [
    "Az1568",
    "joe_oblivian",
    "legoktm",
    "ircservserv-wm",
]
crats = [
    "akosiaris",
    "effie",
    "jayme",
    "mutante",
    "rzl",
]
ops = [
]
plus_o = [
    "wmopbot",
]
autovoice = [
    "wikibugs",
]
global_bans = true
libera_staff = true
