founders = [
    "Az1568",
    "joe_oblivian",
    "paravoid",
    "ircservserv-wm",
]
crats = [
    "legoktm",
]
ops = [
    "manuel",
]
plus_o = [
    "*!*@libera/staff/*",
    "wmopbot",
]
global_bans = true
