founders = [
    "Az1568",
    "legoktm",
    "quiddity",
    "ircservserv-wm",
]
crats = [
    "p858snake",
]
ops = [
    "ashley"
]
plus_o = [
    "wmopbot",
]
global_bans = true
libera_staff = true
